spring:
  cloud:
    config:
      uri: http://localhost:8888  # Config Server'a bağlanma URI'si (HTTP üzerinden erişim)
  application:
    name: charge-square-external-service-application  # Mikroservis adı
