version: '3'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped

  redisinsight:
    image: 'redislabs/redisinsight:1.14.0'
    ports:
      - '8001:8001'