server:
  port: 80

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: chargestations
          uri: http://localhost:9090
          predicates:
            - Path=/stations/**

        - id: get_all_stations_route
          uri: http://localhost:9090
          predicates:
            - Path=/dev/v1/stations/get-all-stations

        - id: get-station-by-id
          uri: http://localhost:9090
          predicates:
            - Path=/dev/v1/stations/get-station-by-id
          filters:
            - AddRequestParameter=stationId,{stationId}


        - id: create-stations
          uri: http://localhost:9090
          predicates:
            - Path=/dev/v1/stations/create-stations

        - id: create-stations
          uri: http://localhost:9090
          predicates:
            - Path=/dev/v1/stations/create-stations



redis:
  host: chargesquare-redis-1     # Redis konteynerinin adı
  port: 6379

cache:
  type: redis                    # Önbellek için Redis kullan
  redis:
    time-to-live: 3600s           # Cache'deki verilerin 1 saat sonra otomatik silinmesini sağlar
