server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/charging_stationsDB  # PostgreSQL veritabanı URL'si
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: create  # Veritabanı şeması otomatik olarak güncellenecek
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate.format_sql: true
        hibernate.use_sql_comments: true
    open-in-view: false
